version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: yelp-analytics-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-yelp_analytics}
      POSTGRES_USER: ${POSTGRES_USER:-yelp_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-yelp_password}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-yelp_user} -d ${POSTGRES_DB:-yelp_analytics}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - yelp-network

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: yelp-analytics-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@yelp-analytics.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - yelp-network
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  yelp-network:
    driver: bridge
