"""Add cluster tables for business clustering

Revision ID: 20c19b4f19df
Revises: b951debc1899
Create Date: 2025-11-26 11:22:57.174424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20c19b4f19df'
down_revision: Union[str, Sequence[str], None] = 'b951debc1899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_runs',
    sa.Column('run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Enum('CITY', 'NEIGHBORHOOD', name='clusterlevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('feature_variant', sa.String(length=100), nullable=False),
    sa.Column('dimred_method', sa.String(length=50), nullable=True),
    sa.Column('dimred_params', sa.JSON(), nullable=True),
    sa.Column('total_entities_processed', sa.Integer(), nullable=False),
    sa.Column('total_clusters_created', sa.Integer(), nullable=False),
    sa.Column('avg_composite_score', sa.Float(), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_cluster_run_level_created', 'cluster_runs', ['level', 'created_at'], unique=False)
    op.create_index(op.f('ix_cluster_runs_level'), 'cluster_runs', ['level'], unique=False)
    op.create_table('clusters',
    sa.Column('cluster_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('cluster_label', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('HDBSCAN', 'KMEANS', 'GMM', 'AGGLOMERATIVE', 'RULE_BASED', name='clustermethod'), nullable=False),
    sa.Column('method_params', sa.JSON(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('silhouette_score', sa.Float(), nullable=True),
    sa.Column('davies_bouldin_score', sa.Float(), nullable=True),
    sa.Column('calinski_harabasz_score', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('avg_stars', sa.Float(), nullable=True),
    sa.Column('avg_review_count', sa.Float(), nullable=True),
    sa.Column('avg_price_range', sa.Float(), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lon', sa.Float(), nullable=True),
    sa.Column('ai_label', sa.String(length=200), nullable=True),
    sa.Column('ai_description', sa.Text(), nullable=True),
    sa.Column('ai_key_characteristics', sa.JSON(), nullable=True),
    sa.Column('top_categories', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['cluster_runs.run_id'], ),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    op.create_index('idx_cluster_label', 'clusters', ['run_id', 'city', 'cluster_label'], unique=False)
    op.create_index('idx_cluster_location', 'clusters', ['city', 'neighborhood'], unique=False)
    op.create_index('idx_cluster_run_location', 'clusters', ['run_id', 'city', 'neighborhood'], unique=False)
    op.create_index(op.f('ix_clusters_city'), 'clusters', ['city'], unique=False)
    op.create_index(op.f('ix_clusters_neighborhood'), 'clusters', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_clusters_run_id'), 'clusters', ['run_id'], unique=False)
    op.create_table('business_clusters',
    sa.Column('business_id', sa.String(length=50), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('distance_to_centroid', sa.Float(), nullable=True),
    sa.Column('cluster_probability', sa.Float(), nullable=True),
    sa.Column('outlier_score', sa.Float(), nullable=True),
    sa.Column('is_noise', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.cluster_id'], ),
    sa.PrimaryKeyConstraint('business_id', 'cluster_id')
    )
    op.create_index('idx_business_cluster_business', 'business_clusters', ['business_id'], unique=False)
    op.create_index('idx_business_cluster_cluster', 'business_clusters', ['cluster_id'], unique=False)
    op.drop_index(op.f('idx_state_category_metrics_lookup'), table_name='state_category_timeline_metrics')
    op.drop_index(op.f('ix_state_category_timeline_metrics_category'), table_name='state_category_timeline_metrics')
    op.drop_index(op.f('ix_state_category_timeline_metrics_state'), table_name='state_category_timeline_metrics')
    op.drop_table('state_category_timeline_metrics')
    op.drop_index(op.f('idx_neighborhood_metrics_lookup'), table_name='neighborhood_timeline_metrics')
    op.drop_index(op.f('ix_neighborhood_timeline_metrics_city'), table_name='neighborhood_timeline_metrics')
    op.drop_index(op.f('ix_neighborhood_timeline_metrics_neighborhood'), table_name='neighborhood_timeline_metrics')
    op.drop_index(op.f('ix_neighborhood_timeline_metrics_state'), table_name='neighborhood_timeline_metrics')
    op.drop_table('neighborhood_timeline_metrics')
    op.drop_index(op.f('idx_city_metrics_lookup'), table_name='city_timeline_metrics')
    op.drop_index(op.f('ix_city_timeline_metrics_city'), table_name='city_timeline_metrics')
    op.drop_index(op.f('ix_city_timeline_metrics_state'), table_name='city_timeline_metrics')
    op.drop_table('city_timeline_metrics')
    op.drop_index(op.f('idx_city_category_metrics_lookup'), table_name='city_category_timeline_metrics')
    op.drop_index(op.f('ix_city_category_timeline_metrics_category'), table_name='city_category_timeline_metrics')
    op.drop_index(op.f('ix_city_category_timeline_metrics_city'), table_name='city_category_timeline_metrics')
    op.drop_index(op.f('ix_city_category_timeline_metrics_state'), table_name='city_category_timeline_metrics')
    op.drop_table('city_category_timeline_metrics')
    op.drop_index(op.f('idx_business_date'), table_name='reviews')
    op.drop_index(op.f('idx_date_business'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_business_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_date'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('idx_state_metrics_lookup'), table_name='state_timeline_metrics')
    op.drop_index(op.f('ix_state_timeline_metrics_state'), table_name='state_timeline_metrics')
    op.drop_table('state_timeline_metrics')
    op.drop_index(op.f('idx_business_metrics_lookup'), table_name='business_timeline_metrics')
    op.drop_index(op.f('ix_business_timeline_metrics_business_id'), table_name='business_timeline_metrics')
    op.drop_table('business_timeline_metrics')
    op.alter_column('businesses', 'attributes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('businesses', 'hours',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('idx_business_categories_trgm'), table_name='businesses', postgresql_ops={'categories': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_business_city_trgm'), table_name='businesses', postgresql_ops={'city': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_business_name_trgm'), table_name='businesses', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_business_name_trgm'), 'businesses', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_business_city_trgm'), 'businesses', ['city'], unique=False, postgresql_ops={'city': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_business_categories_trgm'), 'businesses', ['categories'], unique=False, postgresql_ops={'categories': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('businesses', 'hours',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('businesses', 'attributes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_table('business_timeline_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('avg_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_sentiment_expected', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('business_timeline_metrics_pkey')),
    sa.UniqueConstraint('business_id', 'period_start', 'period_type', name=op.f('uq_business_period'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_business_timeline_metrics_business_id'), 'business_timeline_metrics', ['business_id'], unique=False)
    op.create_index(op.f('idx_business_metrics_lookup'), 'business_timeline_metrics', ['business_id', 'period_type', 'period_start'], unique=False)
    op.create_table('state_timeline_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('avg_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_sentiment_expected', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('business_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('state_timeline_metrics_pkey')),
    sa.UniqueConstraint('state', 'period_start', 'period_type', name=op.f('uq_state_period'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_state_timeline_metrics_state'), 'state_timeline_metrics', ['state'], unique=False)
    op.create_index(op.f('idx_state_metrics_lookup'), 'state_timeline_metrics', ['state', 'period_type', 'period_start'], unique=False)
    op.create_table('reviews',
    sa.Column('review_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stars', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('useful', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('funny', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cool', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sentiment_label', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('sentiment_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('prob_negative', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('prob_neutral', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('prob_positive', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sentiment_score_prob_diff', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sentiment_score_expected', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sentiment_score_logit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], name=op.f('reviews_business_id_fkey')),
    sa.PrimaryKeyConstraint('review_id', name=op.f('reviews_pkey'))
    )
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_reviews_date'), 'reviews', ['date'], unique=False)
    op.create_index(op.f('ix_reviews_business_id'), 'reviews', ['business_id'], unique=False)
    op.create_index(op.f('idx_date_business'), 'reviews', ['date', 'business_id'], unique=False)
    op.create_index(op.f('idx_business_date'), 'reviews', ['business_id', 'date'], unique=False)
    op.create_table('city_category_timeline_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('avg_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_sentiment_expected', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('business_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('city_category_timeline_metrics_pkey')),
    sa.UniqueConstraint('state', 'city', 'category', 'period_start', 'period_type', name=op.f('uq_city_category_period'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_city_category_timeline_metrics_state'), 'city_category_timeline_metrics', ['state'], unique=False)
    op.create_index(op.f('ix_city_category_timeline_metrics_city'), 'city_category_timeline_metrics', ['city'], unique=False)
    op.create_index(op.f('ix_city_category_timeline_metrics_category'), 'city_category_timeline_metrics', ['category'], unique=False)
    op.create_index(op.f('idx_city_category_metrics_lookup'), 'city_category_timeline_metrics', ['state', 'city', 'category', 'period_type', 'period_start'], unique=False)
    op.create_table('city_timeline_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('avg_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_sentiment_expected', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('business_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('city_timeline_metrics_pkey')),
    sa.UniqueConstraint('state', 'city', 'period_start', 'period_type', name=op.f('uq_city_period'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_city_timeline_metrics_state'), 'city_timeline_metrics', ['state'], unique=False)
    op.create_index(op.f('ix_city_timeline_metrics_city'), 'city_timeline_metrics', ['city'], unique=False)
    op.create_index(op.f('idx_city_metrics_lookup'), 'city_timeline_metrics', ['state', 'city', 'period_type', 'period_start'], unique=False)
    op.create_table('neighborhood_timeline_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('neighborhood', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('avg_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_sentiment_expected', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('business_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('neighborhood_timeline_metrics_pkey')),
    sa.UniqueConstraint('state', 'city', 'neighborhood', 'period_start', 'period_type', name=op.f('uq_neighborhood_period'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_neighborhood_timeline_metrics_state'), 'neighborhood_timeline_metrics', ['state'], unique=False)
    op.create_index(op.f('ix_neighborhood_timeline_metrics_neighborhood'), 'neighborhood_timeline_metrics', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_neighborhood_timeline_metrics_city'), 'neighborhood_timeline_metrics', ['city'], unique=False)
    op.create_index(op.f('idx_neighborhood_metrics_lookup'), 'neighborhood_timeline_metrics', ['state', 'city', 'neighborhood', 'period_type', 'period_start'], unique=False)
    op.create_table('state_category_timeline_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('avg_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_sentiment_expected', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('business_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('state_category_timeline_metrics_pkey')),
    sa.UniqueConstraint('state', 'category', 'period_start', 'period_type', name=op.f('uq_state_category_period'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_state_category_timeline_metrics_state'), 'state_category_timeline_metrics', ['state'], unique=False)
    op.create_index(op.f('ix_state_category_timeline_metrics_category'), 'state_category_timeline_metrics', ['category'], unique=False)
    op.create_index(op.f('idx_state_category_metrics_lookup'), 'state_category_timeline_metrics', ['state', 'category', 'period_type', 'period_start'], unique=False)
    op.drop_index('idx_business_cluster_cluster', table_name='business_clusters')
    op.drop_index('idx_business_cluster_business', table_name='business_clusters')
    op.drop_table('business_clusters')
    op.drop_index(op.f('ix_clusters_run_id'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_neighborhood'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_city'), table_name='clusters')
    op.drop_index('idx_cluster_run_location', table_name='clusters')
    op.drop_index('idx_cluster_location', table_name='clusters')
    op.drop_index('idx_cluster_label', table_name='clusters')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_cluster_runs_level'), table_name='cluster_runs')
    op.drop_index('idx_cluster_run_level_created', table_name='cluster_runs')
    op.drop_table('cluster_runs')
    # ### end Alembic commands ###
