"""Initial migration - create business and photo tables

Revision ID: 7907ddabd6f3
Revises: 
Create Date: 2025-11-01 00:08:56.033907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7907ddabd6f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('business_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Float(), nullable=False),
    sa.Column('is_open', sa.Integer(), nullable=False),
    sa.Column('photo_count', sa.Float(), nullable=False),
    sa.Column('categories', sa.String(length=500), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('hours', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_index('idx_location', 'businesses', ['city', 'state'], unique=False)
    op.create_index('idx_stars_reviews', 'businesses', ['stars', 'review_count'], unique=False)
    op.create_index(op.f('ix_businesses_city'), 'businesses', ['city'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_index(op.f('ix_businesses_state'), 'businesses', ['state'], unique=False)
    op.create_table('photos',
    sa.Column('photo_id', sa.String(length=50), nullable=False),
    sa.Column('business_id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_index('idx_business_label', 'photos', ['business_id', 'label'], unique=False)
    op.create_index(op.f('ix_photos_business_id'), 'photos', ['business_id'], unique=False)
    op.create_index(op.f('ix_photos_label'), 'photos', ['label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_label'), table_name='photos')
    op.drop_index(op.f('ix_photos_business_id'), table_name='photos')
    op.drop_index('idx_business_label', table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_businesses_state'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_city'), table_name='businesses')
    op.drop_index('idx_stars_reviews', table_name='businesses')
    op.drop_index('idx_location', table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
