"""add_neighborhood_geojson_file_column

Revision ID: b8e47417e2e8
Revises: d44bad367e45
Create Date: 2025-11-26 14:54:07.543856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e47417e2e8'
down_revision: Union[str, Sequence[str], None] = 'd44bad367e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('neighborhood_geojson_file', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'neighborhood_geojson_file')
    # ### end Alembic commands ###
