"""Add attribute_patterns column to clusters table

Revision ID: d44bad367e45
Revises: 20c19b4f19df
Create Date: 2025-11-26 11:37:35.836794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44bad367e45'
down_revision: Union[str, Sequence[str], None] = '20c19b4f19df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('attribute_patterns', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'attribute_patterns')
    # ### end Alembic commands ###
